// 自動生成: scripts/gen-world-regions.cjs（参考画像 aaaaaa.png より）
// 'A'..'J'=区分/'.'=海。200x100。worldMap.ts の陸/海と一致（陸橋含む）。
export type WorldRegionMeta = { id: number; code: string; ja: string; r: number; g: number; b: number };
export const WORLD_REGIONS: WorldRegionMeta[] = [
  { id: 0, code: "NA", ja: "北アメリカ", r: 160, g: 200, b: 240 },
  { id: 1, code: "NAsia", ja: "北アジア", r: 40, g: 80, b: 240 },
  { id: 2, code: "EU", ja: "ヨーロッパ", r: 40, g: 200, b: 80 },
  { id: 3, code: "EAsia", ja: "東アジア", r: 240, g: 80, b: 80 },
  { id: 4, code: "NAfr", ja: "北アフリカ", r: 225, g: 150, b: 70 },
  { id: 5, code: "CAsia", ja: "中央アジア", r: 200, g: 200, b: 40 },
  { id: 6, code: "SA", ja: "南アメリカ", r: 150, g: 60, b: 160 },
  { id: 7, code: "SAfr", ja: "南アフリカ", r: 40, g: 200, b: 240 },
  { id: 8, code: "SEAsia", ja: "東南アジア", r: 240, g: 160, b: 240 },
  { id: 9, code: "AU", ja: "オーストラリア", r: 140, g: 215, b: 50 },
];
export const WORLD_REGION_WIDTH = 200;
export const WORLD_REGION_HEIGHT = 100;
export const WORLD_REGION_ROWS: string[] = [
  "........................................................................................................................................................................................................",
  "........................................................................................................................................................................................................",
  "........................................................................................................................................................................................................",
  "........................................................................................................................................................................................................",
  "........................................................................................................................................................................................................",
  "...................................................................................................................................................................C......................CC............",
  "................................................................................................................................................................AAACCCCCCCCC...CC...CCCCCCCCCC..........",
  "..............................................................BB..............................................................................................AAAAACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC.....",
  "....................CCCCCCC..................B..BB...........BBBBBB.........................................................................................AAAAAAACCCCC..CCCCCCCCCCCCCCCCCCCCCCCC......",
  ".....................CCCCCC.................BBBBBB..............BBB.BB................................................................................AA....AAAAAAACCC....CCCCCCCCCCCCCCCCCCCCCC........",
  "......................CC...................BBBBB...................B..............................................................................AA..AAA.AA.AAAAAAAC..CCCCCCCCCCCCCCCCCCCCCCCC.........",
  "......................C....................BBB....................BBBBBB......................................................................AAAAA..A....AA..AAAAAAA...CCCCCCCCCCCCCCCCCCCCCCC.........",
  ".......................C..................BB...............B.BBBBBBBBBBBB....................................................................AAAAA.AA.AAAAAAA.AAAAAA.....CCCCCCCCCCCCCCCCCCCCCCC........",
  ".......................C.................BBB..............BBBBBBBBBBBBBBB............AAAAAA.....................................................AAAAAA.AAAAAAAAAAAA..........CCCCCCCCCCCCCCCCCCC........",
  "........................C...............BBB.......BB....BBBBBBBBBBBBBBBB.............AAA....................................................AAA..AA.......AAAAAAAAA...........CCCCCCCCCCCCCCCCC.........",
  "........................C...............BBB.......BB..BBBBBBBBBBBBBBBBBBBBBB.BBB......A.....................................................AAAAA....A..AA.AAAAAAA.............CCCCCCCCCCCCCC...........",
  ".........................C.CCC............BB....BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB......BBBB.................................AA..............AAAAAAAAAAA.AAAAA..AAAAAAAA..........CCCCCCCCCCCCCC..........",
  ".......................CCCCCCCC.............BB...BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.B.BBBBBBBBB...............A............AAAAA.A............A..AAAAAAAA.AAAA..AAAAAAAAA........CCCCCCCCCCCCCCC..........",
  "......................CCCCCCCCCCC......B.....BBB.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.BB..........AA...........AAAAAAAAAAAAA..AAAAAAA..AAAAAAAA..AAA.AAAAAAAAAAA.......CCCCCCCCCCCCC...........",
  ".....................CCCCCCCCCCCCCC..B.BBB.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB....BBBB..A..........AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.A.AAAA.AA..AAAAA.......CCCCCCCCCC..............",
  ".....................CCCCCCCCCCCCCC..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.........AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA....AAAAA....CCCCCCCCCC...............",
  "....................CCCCCCCCCCCC.CCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB........AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA....AAAAAAA...CCCCCCC..................",
  "....................CCCCC..CCCCCCC.CBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB......A..AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...AAAAAAAAA....CCCCCC..................",
  "..................CCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.........AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA..A.AAAAA......CCCC...................",
  ".................CCCCCC..CCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.....B......AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.AAA.....AAA.........C....................",
  ".................CCCCCCC.CCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.......B.....AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.....AAAAA.AA...............................",
  "...........CC....CC.CCCC..CCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.BBBBBBBBB..........A..AAAAAAAA.A.....AAAAAAAAAAAAAAAAAAAAAAA........AAAAA................................",
  "..........CCC.....CCCCC...CCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDDDDDDDBBBBBBBBBBBBBBBBBBBBBB..BBB...............A..AA...AAAA.......AAAAAAAAAAAAAAAAAAAAAA........AAAAAAAA.............................",
  "...........CC.....CCCC..CCCCCCCCCCCBBFFFFFFFFBBBBBBBBBBBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD........BBB.................A......AA..........AAAAAAAAAAAAAAAAAAAAAAAA......AAAAAAAA............................",
  "..........CCCC....CCC..CCCCCCCCCCCCFFFFFFFFFFFFFFFFFBBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD........BBBB..................A..AAA............AAAAAAAAAAAAAAAAAAAAAAAAA....AAAAAAAAA............................",
  "........CCC.CC..CCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.........BBB....................AAAA.............AAAAAAAAAAAAAAAAAAAAAAAAAAA..AAAAAAAAAAA..........................",
  ".........CCCCCC.CCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.....BB.................A..AAA................A.AAAAAAAAAAAAAAAAAAAAAAAA.AAAAAAAAAAAA..........................",
  "...........CCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.....BB..............AAAAAA......................AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.........................",
  "...........CCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.....BB..........................................AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.........................",
  "...........CCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.....B...........................................AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...AAA........................",
  ".............CCCCCCCCCCCCCCCCCCCCFFFFFF..FFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.DD...................................................AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...AAA........................",
  ".............CCCCCCCCCCCCCCCC.CC.FFFFF.FFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD..D...D...............................................AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA..A........................",
  "..........CCCCCC.C.CC.CCCCCCC.....FFFF..FFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD..D..D................................................AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...........................",
  "..........CCCCCC..C.CCCCCCCCC.CCF..FFFF..FFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD..DDDD.................................................AAAAAAAAAAAAAAAAAAAAAAAAAAAAA.AA.............................",
  "..........CCCC....CC.CC.CC.CCCCCFFFFFFF..FFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDD.....DD...................................................AAAAAAAAAAAAAAAAAAAAAAAAAAAAA................................",
  "..........CCCC......CCC.CC.CCCCCFFFFFFF..FFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDD..DDD......D....................................................AAAAAAAAAAAAAAAAAAAAAAAAAAA..................................",
  "...........CC.EEEEEECC...C..CCCCFFFFFFFF.FFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDD.DDD....DD.....................................................AAAAAAAAAAAAAAAAAAAAAAAAA...................................",
  "...........EEEEEEEEE..........C.FFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDD..DD...DDD.....................................................AAAAAAAAAAAAAAAAAAAAAAAAA...................................",
  ".........EEEEEEEEEEEE....E......FFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDD...D..DDDD....................................................AA.AAAAAAAAAAAAAAAAAAAAAAA....................................",
  ".........EEEEEEEEEEEEEE.EEEE...FFFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDD.....DDD....................................................AA....AAAAAAAAAAAAAAAAAAAAA.....................................",
  ".........EEEEEEEEEEEEEEEEEEEEEFFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDD...DD....................................................AA......AAAAAAAAAAAAAAAAAAAA......................................",
  ".......EEEEEEEEEEEEEEEEEEEEEEEFFFFFFFFF.FFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDD....D..................................................AA.........AAAAAAAAAAAAAAA.AAA......................................",
  ".......EEEEEEEEEEEEEEEEEEEEEEEFFFFFFFFF..FFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDD.....................................................AA...........AA.AAAAAAAA......AA......................................",
  "......EEEEEEEEEEEEEEEEEEEEEEEEEFFFFFFFFF.FF.FFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDD....................................................AA..............AA.AAAAAA........A......................................",
  ".....EEEEEEEEEEEEEEEEEEEEEEEEEEFFFFFFFFFFFFF....FFFFFFFFFFDDDDDDDDIIIIIIIII.D.................................................AA.................AAAAAAAA.........GG....................................",
  ".....EEEEEEEEEEEEEEEEEEEEEEEEEEEF.FFFFFFFFFF.....FFFFFFFFFFDDDDDIIIIIIIII...D...............................................AA......................AAAAA.......GGGG....................................",
  ".....EEEEEEEEEEEEEEEEEEEEEEEEEEEE..FFFFFFFF.......FFFFFFFF...IIIIIIIIII.....D.............................................AA........................AAAAA....AA...GGGG..................................",
  "......EEEEEEEEEEEEEEEEEEEEEEEEEEEE.FFFFFFFF........FFFFFF.....IIIIIII.I.....I..............................................A.........................AAAAAAAAA.....GGGGGGG..............................",
  ".....EEEEEEEEEEEEEEEEEEEEEEEEEEEEE..FFFFFF.........FFFFF......IIIIIII......II.........................................................................AAAAAAAA.....G.GGGGG..............................",
  "....EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE.EFFF............FFF.........IIIIII.....II............I................................................................AAGGGG...........G............................",
  "..EE..EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE..............FFF.........IIIIII......III.........I.I................................................................GGGGGG..........G............................",
  ".E.....EEEEEEEEEEEEEEEEEEEEEEEEEEEEE.EEE............FFF.........I.IIII......III............I........J.........................................................GG......G....G............................",
  "E......EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE.............FF.........I..II.....II.II.............AA......J..........................................................GG.G.GGGGGGGG............................",
  "........EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE...............FF........II...........IIIIIII........A.A...JJ............................................................GGGGGGGGGGGG..........................EE",
  ".........EEEEE..EEEEEEEEEEEEEEEEEEEEEEE...............FF.........II......II.III....I.......A...AAA..JJ.............................................................GGGGGGGGGGGGG.....................E..",
  "..........E.......EHHHHHHHHHEEEEEEEEEE.........................IIII.....III....................A..A................................................................GGGGGGGGGGGGGG...................E...",
  "...................HHHHHHHHHHHHHHHHHH..........................IIIII...IIII...................A...J................................................................GGGGGGGGGGGGGGG................GG....",
  "..................HHHHHHHHHHHHHHHHHH............................IIII.IIIIIIIII.II.............A....J..............................................................GGGGGGGGGGGGGGGG...............G......",
  "..................HHHHHHHHHHHHHHHHH..............................III..IIII.II..I.II..........I.....JJJA...........................................................GGGGGGGGGGGGGGGGG.............G.......",
  "...................HHHHHHHHHHHHHHH...............................IIII.IIII.II..IIIIIIII......I...................................................................GGGGGGGGGGGGGGGGGGGG.........GG........",
  "....................HHHHHHHHHHHHHH................................II.......III..I.IIIIIII..II....................................................................GGGGGGGGGGGGGGGGGGGGGG......G..........",
  "....................HHHHHHHHHHHHHH.................................IIIII.....I.I...I.IIIIIIII....................................................................GGGGGGGGGGGGGGGGGGGGGGGG...G...........",
  "....................HHHHHHHHHHHHHH...................................IIIIIIIIII......IIIIII..AAA.........A........................................................GGGGGGGGGGGGGGGGGGGGGGG.GG............",
  "....................HHHHHHHHHHHHHHH.......................................IIIII.......II.III....AA.......A........................................................GGGGGGGGGGGGGGGGGGGGGGGG..............",
  "....................HHHHHHHHHHHHHHH...............................................JJ...I...I.....AA.....A..........................................................GGGGGGGGGGGGGGGGGGGGGG...............",
  "....................HHHHHHHHHHHHHHH...HH.........................................JJJ..JJ...........JJ...A.....AA...................................................GGGGGGGGGGGGGGGGGGGGG................",
  "....................HHHHHHHHHHHHHH.HHHH.......................................JJJJJJ...JJ..........J.JJA....AA......................................................GGGGGGGGGGGGGGGGGGG.................",
  "....................HHHHHHHHHHHHH...HHH......................................JJJJJJJJJJJJ..........J....AAAA.A.......................................................GGGGGGGGGGGGGGGGGG.................",
  "....................HHHHHHHHHHHH....HHH....................................JJJJJJJJJJJJJJJ.........A.....A....J.......................................................GGGGGGGGGGGGGGGGG.................",
  "....................HHHHHHHHHHHH...HHH....................................JJJJJJJJJJJJJJJJJ.......AA..........J........................................................GGGGGGGGGGGGGGG..................",
  ".....................HHHHHHHHHH.....HH...................................JJJJJJJJJJJJJJJJJJJ.......A...................................................................GGGGGGGGGGGGGG...................",
  ".....................HHHHHHHHHH.........................................JJJJJJJJJJJJJJJJJJJJJ..........................................................................GGGGGGGGGGGG.....................",
  "......................HHHHHHHH...........................................JJJJJJJJJJJJJJJJJJJJ..........................................................................GGGGGGGGGGG......................",
  "......................HHHHHHHH...........................................JJJJJJJJJJJJJJJJJJJJ.........................................................................GGGGGGGGGGGG......................",
  "......................HHHHHHH............................................JJJJJJJJJJJJJJJJJJJJ.........................................................................GGGGGGGGGGG.......................",
  ".......................HHHH...............................................JJJJJJ..JJJJJJJJJJJ.........................................................................GGGGGGGGGG........................",
  ".........................................................................JJJJJ.....JJJJJJJJJ..........................................................................GGGGGGGGGG........................",
  "..........................................................................JJ.........JJJJJJJ...........J..............................................................GGGGGGGG..........................",
  "......................................................................................JJJJJ............JJJ...........................................................GGGGGGGGG..........................",
  ".......................................................................................J...............JJJ...........................................................GGGGGGGG...........................",
  "........................................................................................JJ............JJJ............................................................GGGGGGG............................",
  "........................................................................................JJJJJ........JJJ.............................................................GGGGGG.............................",
  ".........................................................................................J...JJJJ....JJ...............................................................GGGG..............................",
  ".................................................................................................JJJJJ...............................................................GGGGG..............................",
  "....................................................................................................J................................................................GGGGG..............................",
  ".....................................................................................................................................................................GGGG...............................",
  ".....................................................................................................................................................................GGGG...............................",
  ".....................................................................................................................................................................GGG....GG..........................",
  ".....................................................................................................................................................................GGGG..GG...........................",
  "......................................................................................................................................................................GGGGG.............................",
  "........................................................................................................................................................................G...............................",
  "........................................................................................................................................................................................................",
  "........................................................................................................................................................................................................",
  "........................................................................................................................................................................................................",
  "........................................................................................................................................................................................................",
];
