// 自動生成: scripts/gen-world-regions.cjs（参考画像 aaaaaa.png より）
// 'A'..'J'=区分/'.'=海。200x100。worldMap.ts の陸/海と一致（陸橋含む）。
export type WorldRegionMeta = { id: number; code: string; ja: string; en: string; r: number; g: number; b: number; labelX?: number; labelY?: number };
export const WORLD_REGIONS: WorldRegionMeta[] = [
  { id: 0, code: "NA", ja: "北アメリカ", en: "N. America", r: 240, g: 130, b: 40 },
  { id: 1, code: "NAsia", ja: "北アジア", en: "N. Asia", r: 40, g: 80, b: 240 },
  // EU は北極の陸地で実ヨーロッパ(左)とグリーンランド(右)が繋がり、全セル重心が海(中央)に来る。
  // ラベルは実ヨーロッパ(左塊・全EUセルの過半 471/796, 重心(22.8,28.4))上に固定。
  { id: 2, code: "EU", ja: "ヨーロッパ", en: "Europe", r: 40, g: 200, b: 80, labelX: 23, labelY: 28 },
  { id: 3, code: "EAsia", ja: "東アジア", en: "E. Asia", r: 240, g: 80, b: 80 },
  { id: 4, code: "NAfr", ja: "北アフリカ", en: "N. Africa", r: 225, g: 150, b: 70 },
  { id: 5, code: "CAsia", ja: "中央アジア", en: "C. Asia", r: 200, g: 200, b: 40 },
  { id: 6, code: "SA", ja: "南アメリカ", en: "S. America", r: 150, g: 60, b: 160 },
  { id: 7, code: "SAfr", ja: "南アフリカ", en: "S. Africa", r: 40, g: 200, b: 240 },
  { id: 8, code: "SEAsia", ja: "東南アジア", en: "SE Asia", r: 240, g: 160, b: 240 },
  { id: 9, code: "AU", ja: "オーストラリア", en: "Australia", r: 140, g: 215, b: 50 },
];
export const WORLD_REGION_WIDTH = 200;
export const WORLD_REGION_HEIGHT = 100;
export const WORLD_REGION_ROWS: string[] = [
  "........................................................................................................................................................................................................",
  "........................................................................................................................................................................................................",
  "........................................................................................................................................................................................................",
  "........................................................................................................................................................................................................",
  "........................................................................................................................................................................................................",
  "...................................................................................................................................................................C......................CC............",
  "................................................................................................................................................................AAACCCCCCCCC...CC...CCCCCCCCCC..........",
  "..............................................................BB..............................................................................................AAAAACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC.....",
  "....................CCCCCCC..................B..BB...........BBBBBB.........................................................................................AAAAAAACCCCC..CCCCCCCCCCCCCCCCCCCCCCCC......",
  ".....................CCCCCC.................BBBBBB..............BBBBBB................................................................................AA....AAAAAAACCC....CCCCCCCCCCCCCCCCCCCCCC........",
  "......................CC...................BBBBB...................B..............................................................................AA..AAA.AAAAAAAAAAC..CCCCCCCCCCCCCCCCCCCCCCCC.........",
  "......................C....................BBB....................BBBBBB......................................................................AAAAAA.AA...AA..AAAAAAA...CCCCCCCCCCCCCCCCCCCCCCC.........",
  "......................C...................BB...............B.BBBBBBBBBBBB....................................................................AAAAA.AAAAAAAAAA.AAAAAA.....CCCCCCCCCCCCCCCCCCCCCCC........",
  "......................CC.................BBB..............BBBBBBBBBBBBBBB............AAAAAA.....................................................AAAAAA.AAAAAAAAAAAA..........CCCCCCCCCCCCCCCCCCC........",
  ".......................CC...............BBB.......BB....BBBBBBBBBBBBBBBB.............AAA....................................................AAA..AA.......AAAAAAAAA...........CCCCCCCCCCCCCCCCC.........",
  "........................CC..............BBB.......BB..BBBBBBBBBBBBBBBBBBBBBB.BBB......A.....................................................AAAAAA...A..AAAAAAAAAA.............CCCCCCCCCCCCCC...........",
  ".........................C.CCC............BBBB..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB......BBBB.................................AA..............AAAAAAAAAAA.AAAAA..AAAAAAAA..........CCCCCCCCCCCCCC..........",
  ".......................CCCCCCCC..............B...BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.B.BBBBBBBBB...............A............AAAAA.A............A..AAAAAAAAAAAAA..AAAAAAAAA........CCCCCCCCCCCCCCCCCCCCCC...",
  "......................CCCCCCCCCCC......B.....BBB.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.BB..........AA...........AAAAAAAAAAAAA..AAAAAAA..AAAAAAAA..AAA.AAAAAAAAAAA.......CCCCCCCCCCCCC.......CC..",
  ".....................CCCCCCCCCCCCCC..B.BBB.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB....BBBB..A..........AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.AAAAAA.AA..AAAAA.......CCCCCCCCCC...........CC.",
  ".....................CCCCCCCCCCCCCC..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.........AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA....AAAAA....CCCCCCCCCC.............CC",
  "C...................CCCCCCCCCCCC.CCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB........AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA....AAAAAAA...CCCCCCC.................C",
  "CC..................CCCCC..CCCCCCC.CBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB......AA.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...AAAAAAAAA....CCCCCC..................",
  ".CC...............CCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.........AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA..A.AAAAA......CCCC...................",
  "..CC.............CCCCCC..CCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB....BB......AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.AAA.....AAA.........C....................",
  "...CC............CCCCCCC.CCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB......BB.....AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.....AAAAA.AA...............................",
  "....CC.....CC....CC.CCCC..CCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.BBBBBBBBB.........BA..AAAAAAAA.A.....AAAAAAAAAAAAAAAAAAAAAAA........AAAAA................................",
  ".....CC...CCC.....CCCCC...CCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDDDDDDDBBBBBBBBBBBBBBBBBBBBBB..BBB...............AA.AA...AAAAA......AAAAAAAAAAAAAAAAAAAAAA........AAAAAAAA.............................",
  "......CC...CC.....CCCC..CCCCCCCCCCCBBFFFFFFFFBBBBBBBBBBBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD........BBB.................AAA....AA..........AAAAAAAAAAAAAAAAAAAAAAAA......AAAAAAAA............................",
  ".......CC.CCCC....CCC..CCCCCCCCCCCCFFFFFFFFFFFFFFFFFBBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD........BBBB..................AA.AAAA...........AAAAAAAAAAAAAAAAAAAAAAAAA....AAAAAAAAA............................",
  "........CCC.CC..CCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.........BBB....................AAAA.............AAAAAAAAAAAAAAAAAAAAAAAAAAA..AAAAAAAAAAA..........................",
  ".........CCCCCC.CCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.....BB.................A...AA................A.AAAAAAAAAAAAAAAAAAAAAAAA.AAAAAAAAAAAA..........................",
  "...........CCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.....BB..............AAAAAAAA....................AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.........................",
  "...........CCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.....BB..........................................AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.........................",
  "...........CCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.....B...........................................AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...AAA........................",
  ".............CCCCCCCCCCCCCCCCCCCCFFFFFFF.FFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.DD...................................................AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...AAA........................",
  ".............CCCCCCCCCCCCCCCC.CC.FFFFF.FFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD..D...D...............................................AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.A........................",
  "..........CCCCCC.CCCC.CCCCCCC.....FFFF..FFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD..D..DD...............................................AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...........................",
  "..........CCCCCC..C.CCCCCCCCC.CCF..FFFF..FFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD..DDDDD................................................AAAAAAAAAAAAAAAAAAAAAAAAAAAAA.AA.............................",
  "..........CCCC....CCCCC.CC.CCCCCFFFFFFF..FFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDD.....DD...................................................AAAAAAAAAAAAAAAAAAAAAAAAAAAAA................................",
  "..........CCCCC.....CCC.CC.CCCCCFFFFFFF..FFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDD..DDD......D....................................................AAAAAAAAAAAAAAAAAAAAAAAAAAA..................................",
  "...........CC.EEEEEECC...C..CCCCFFFFFFFF.FFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDD....DD.....................................................AAAAAAAAAAAAAAAAAAAAAAAAA...................................",
  "...........EEEEEEEEE..........C.FFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDD..DD...DDD.....................................................AAAAAAAAAAAAAAAAAAAAAAAAA...................................",
  ".........EEEEEEEEEEEE....E......FFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDD...D..DDDD.....................................................AAAAAAAAAAAAAAAAAAAAAAAAA....................................",
  ".........EEEEEEEEEEEEEE.EEEE...FFFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDD.....DDD......................................................AA..AAAAAAAAAAAAAAAAAAAAA.....................................",
  ".........EEEEEEEEEEEEEEEEEEEEEFFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDD...DD.......................................................AA...AAAAAAAAAAAAAAAAAAAA......................................",
  ".......EEEEEEEEEEEEEEEEEEEEEEEFFFFFFFFF.FFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDD....D......................................................AA.....AAAAAAAAAAAAAAA.AAA......................................",
  ".......EEEEEEEEEEEEEEEEEEEEEEEFFFFFFFFF..FFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDD..........................................................AA......AA.AAAAAAAA......AA......................................",
  "......EEEEEEEEEEEEEEEEEEEEEEEEEFFFFFFFFF.FF.FFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDD.........................................................AA........AAAAAAAAA........AA.....................................",
  ".....EEEEEEEEEEEEEEEEEEEEEEEEEEFFFFFFFFFFFFFF...FFFFFFFFFFDDDDDDDDIIIIIIIII.D........................................................AA..........AAAAAAAA.........GG....................................",
  ".....EEEEEEEEEEEEEEEEEEEEEEEEEEEF.FFFFFFFFFF.....FFFFFFFFFFDDDDDIIIIIIIII...D.......................................................AA..............AAAAA.......GGGG....................................",
  ".....EEEEEEEEEEEEEEEEEEEEEEEEEEEE..FFFFFFFF.......FFFFFFFF...IIIIIIIIII.....D.............................................AAAAAAAAAAA...............AAAAA....AA...GGGG..................................",
  "......EEEEEEEEEEEEEEEEEEEEEEEEEEEE.FFFFFFFF........FFFFFF.....IIIIIII.I.....I..............................................A.........................AAAAAAAAA.....GGGGGGG..............................",
  ".....EEEEEEEEEEEEEEEEEEEEEEEEEEEEE..FFFFFF.........FFFFF......IIIIIII......II.........................................................................AAAAAAAA.....G.GGGGG..............................",
  ".....EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE.EFFF............FFF.........IIIIII.....II............I................................................................AAGGGG...........G............................",
  "....EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE..............FFF.........IIIIII......III.........II.................................................................GGGGGG..........G............................",
  "...EE..EEEEEEEEEEEEEEEEEEEEEEEEEEEEE.EEE............FFF.........I.IIII......III.........I...........J.........................................................GG......G....G............................",
  "..EE...EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE.............FF.........I..II.....IIIII.........I........AJJJ..........................................................GG.G.GGGGGGGG............................",
  ".EE.....EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE...............FF........II...........III...I....I.......AA..JJ..........................................................GGGGGGGGGGGG............................",
  "EE.......EEEEE..EEEEEEEEEEEEEEEEEEEEEEE...............FF.........II......II.III....I....AAAA...AA....J.............................................................GGGGGGGGGGGGG........................",
  "E.........E.......EHHHHHHHHHEEEEEEEEEE.........................IIII.....III.......II....A......A...................................................................GGGGGGGGGGGGGG......................E",
  "...................HHHHHHHHHHHHHHHHHH..........................IIIII...IIII......II.....A......A...................................................................GGGGGGGGGGGGGGG....................EE",
  "..................HHHHHHHHHHHHHHHHHH............................IIII.IIIIIIIII.III.....II.....AA..................................................................GGGGGGGGGGGGGGGG...................EE.",
  "..................HHHHHHHHHHHHHHHHH..............................III..IIII.II..I.II...II.....IIAJJJJJJA...........................................................GGGGGGGGGGGGGGGGG.................GE..",
  "...................HHHHHHHHHHHHHHH...............................IIII.IIII.II..IIIIIIII.....II...................................................................GGGGGGGGGGGGGGGGGGGG..............GG...",
  "....................HHHHHHHHHHHHHH................................II.......IIIIII.IIIIIII..II....................................................................GGGGGGGGGGGGGGGGGGGGGG...........GG....",
  "....................HHHHHHHHHHHHHH.................................IIIII......II...I.IIIIIIII....................................................................GGGGGGGGGGGGGGGGGGGGGGGG........GG.....",
  "....................HHHHHHHHHHHHHH...................................IIIIIIIIII......IIIIII.IAAAA........A........................................................GGGGGGGGGGGGGGGGGGGGGGG.......GG......",
  "....................HHHHHHHHHHHHHHH.......................................IIIII.......II.IIII...AA.......A........................................................GGGGGGGGGGGGGGGGGGGGGGG......GG.......",
  "....................HHHHHHHHHHHHHHH...............................................JJ...I...I.....A.......A.........................................................GGGGGGGGGGGGGGGGGGGGGGGGGGGGG........",
  "....................HHHHHHHHHHHHHHH...HH.........................................JJJ..JJ.........AA......A.AAAAA...................................................GGGGGGGGGGGGGGGGGGGGG................",
  "....................HHHHHHHHHHHHHHHHHHH.......................................JJJJJJ...JJ.........JJ.....AAA..A.....................................................GGGGGGGGGGGGGGGGGGG.................",
  "....................HHHHHHHHHHHHH...HHH......................................JJJJJJJJJJJJ..........JJJAAAAA...A......................................................GGGGGGGGGGGGGGGGGG.................",
  "....................HHHHHHHHHHHH....HHH....................................JJJJJJJJJJJJJJJ.........A.....A....J.......................................................GGGGGGGGGGGGGGGGG.................",
  "....................HHHHHHHHHHHH...HHH....................................JJJJJJJJJJJJJJJJJ.......AA..........J........................................................GGGGGGGGGGGGGGG..................",
  ".....................HHHHHHHHHH.....HH...................................JJJJJJJJJJJJJJJJJJJ.......A...................................................................GGGGGGGGGGGGGG...................",
  ".....................HHHHHHHHHH.........................................JJJJJJJJJJJJJJJJJJJJJ..........................................................................GGGGGGGGGGGG.....................",
  "......................HHHHHHHH...........................................JJJJJJJJJJJJJJJJJJJJ..........................................................................GGGGGGGGGGG......................",
  "......................HHHHHHHH...........................................JJJJJJJJJJJJJJJJJJJJ.........................................................................GGGGGGGGGGGG......................",
  "......................HHHHHHH............................................JJJJJJJJJJJJJJJJJJJJ.........................................................................GGGGGGGGGGG.......................",
  ".......................HHHH...............................................JJJJJJ..JJJJJJJJJJJ.........................................................................GGGGGGGGGG........................",
  ".........................................................................JJJJJ.....JJJJJJJJJ..........................................................................GGGGGGGGGG........................",
  "..........................................................................JJ.........JJJJJJJ...........J..............................................................GGGGGGGG..........................",
  "......................................................................................JJJJJ............JJJ...........................................................GGGGGGGGG..........................",
  ".......................................................................................JJ..............JJJ...........................................................GGGGGGGG...........................",
  "........................................................................................JJ............JJJ............................................................GGGGGGG............................",
  "........................................................................................JJJ..........JJJ.............................................................GGGGGG.............................",
  ".........................................................................................JJJ.........JJ...............................................................GGGG..............................",
  "...........................................................................................JJJJJJJJJJJ...............................................................GGGGG..............................",
  "....................................................................................................J................................................................GGGGG..............................",
  ".....................................................................................................................................................................GGGG...............................",
  ".....................................................................................................................................................................GGGG...............................",
  ".....................................................................................................................................................................GGG....GG..........................",
  ".....................................................................................................................................................................GGGGGGGG...........................",
  "......................................................................................................................................................................GGGG..............................",
  "........................................................................................................................................................................G...............................",
  "........................................................................................................................................................................................................",
  "........................................................................................................................................................................................................",
  "........................................................................................................................................................................................................",
  "........................................................................................................................................................................................................",
];
